# -*- coding: utf-8 -*-
"""Mechine Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/131-HCWtY0eo9-1ehB6hdGHxEHLmFGJ70

##Regresi
"""

#Import Library
import numpy as np
import pandas as pd
import statsmodels.api as sm

# Membuat DataFrame dari data yang diberikan
data = {
 'Partisipan': np.arange(1, 11),
 'PMakan': [50, 40, 60, 55, 45, 65, 70, 75, 80, 90],
 'PTranspor': [20, 25, 30, 35, 40, 50, 55, 60, 65, 70],
 'BB': [60, 55, 65, 70, 62, 75, 80, 85, 90, 95]}
df = pd.DataFrame(data)

# Memisahkan variabel independen dan dependen
X = df[['PMakan', 'PTranspor']]
y = df['BB']
X = sm.add_constant(X)
model = sm.OLS(y, X)
results = model.fit()
print(results.summary())

"""##Visual 3D"""

import numpy as np
import pandas as pd
import statsmodels.api as sm
import plotly.graph_objects as go

data = {
 "Partisipan": np.arange(1, 11),
 "Peng Makanan": [ 50, 40, 60, 55, 45, 65, 70, 75, 80, 990],
 "Peng Transportasi": [ 20, 25, 30, 35, 40, 50, 55, 60, 65, 70 ],
 "Berat Badan": [ 60, 55, 65, 70, 62, 75, 80, 85, 90, 95 ]}
df = pd.DataFrame(data)

# Variabel independen
X = df[ [ "Peng Makanan", "Peng Transportasi" ]]
# Variabel dependen
y = df["Berat Badan"]

# 4. MENAMBAHKAN INTERCEPT
X_model = sm.add_constant(X)
# 5. ESTIMASI MODEL OLS
model = sm.OLS(y, X_model)
results = model.fit()

# 6. MENAMPILKAN RINGKASAN HASIL REGRESI
print("\n")
print("=" * 70)
print(" HASIL REGRESI LINEAR BERGANDA")
print("=" * 70)
print(results.summary())

# 7. MENGAMBIL KOEFISIEN REGRESI
intercept = results.params["const"]
coef_makanan = results.params["Peng Makanan"]
coef_transportasi = results.params[ "Peng Transportasi"]
r_squared = results.rsquared
adjusted_r_squared = results.rsquared_adj

# 8. MEMBUAT PERSAMAAN REGRESI
persamaan = (
 f"Ŷ = {intercept:.3f}"
 f" + ({coef_makanan:.3f}) X₁"
 f" + ({coef_transportasi:.3f}) X₂")
print("\n")
print("=" * 70)
print(" PERSAMAAN REGRESI")
print("=" * 70)
print(persamaan)
print(f"\nR² = {r_squared:.4f}")
print(f"Adjusted R² = {adjusted_r_squared:.4f}")



# 9. MENGHITUNG NILAI PREDIKSI
df["Prediksi"] = results.predict(X_model)
print("\n")
print("=" * 70)
print(" DATA AKTUAL & PREDIKSI")
print("=" * 70)
print(
 df[[ "Partisipan", "Peng Makanan", "Peng Transportasi", "Berat Badan", "Prediksi"]].round(2))

# 10. MEMBUAT GRID UNTUK BIDANG REGRESI
x1 = np.linspace(
 df["Peng Makanan"].min(),
 df["Peng Makanan"].max(),
 40)
x2 = np.linspace(
 df["Peng Transportasi"].min(),
 df["Peng Transportasi"].max(),
 40)
X1, X2 = np.meshgrid(x1, x2)

# 11. MENGHITUNG NILAI Y PADA BIDANG REGRESI
Y = ( intercept + coef_makanan * X1 + coef_transportasi * X2)

# 12. MEMBUAT FIGURE 3D
fig = go.Figure()



fig = go.Figure()
# 13. MENAMPILKAN DATA AKTUAL
fig.add_trace(
 go.Scatter3d(
 x=df["Peng Makanan"],
 y=df["Peng Transportasi"],
 z=df["Berat Badan"],
 mode="markers",
 marker=dict(
 size=7,
 color="red",
 opacity=0.9
 ),
 name="Data Aktual",
 text=[
 f"Partisipan {p}"
 for p in df["Partisipan"]
 ],
 hovertemplate=(
 "<b>%{text}</b><br>" "Peng. Makanan: %{x}<br>"
 "Peng. Transportasi: %{y}<br>"
 "Berat Badan: %{z}"
 "<extra></extra>"
 )
 )
)
# 14. MENAMPILKAN BIDANG REGRESI
fig.add_trace(
 go.Surface(
 x=X1, y=X2, z=Y,
 opacity=0.60,
 colorscale="Viridis",
 name="Regression Plane",
 hovertemplate=(
 "Peng. Makanan: %{x:.2f}<br>"
 "Peng. Transportasi: %{y:.2f}<br>"
 "Prediksi Y: %{z:.2f}"
 "<extra></extra>"
 )
 )
)

# 15. MENGATUR TAMPILAN GRAFIK
fig.update_layout(
 title={
 "text": (
 "REGRESI LINEAR BERGANDA 3D"
 "<br>"
 f"<sup>{persamaan} | "
 f"R² = {r_squared:.3f}</sup>" ), "x": 0.5 },
 scene={
 "xaxis": {"title": "Pengeluaran Makanan (X₁)" },
 "yaxis": {"title": "Pengeluaran Transportasi (X₂)" },
 "zaxis": { "title": "Berat Badan (Y)" } },
 width=1000,
 height=750,
 margin={
 "l": 0, "r": 0, "b": 0, "t": 100 },
 legend={ "x": 0.02, "y": 0.98 }
)

# 16. MENAMPILKAN GRAFIK
fig.show()

"""##Contoh Lain"""

import numpy as np
from scipy import stats

data = np.array([167, 184, 192, 198, 200, 202, 210, 211, 212, 215, 216, 217, 218, 220, 225,
                225, 226, 230, 230, 230, 230, 231, 232, 232, 232, 234, 234, 236, 236, 238,
                240, 243, 246, 247, 248, 254, 254, 254, 256, 256, 258, 263, 264, 267, 267,
                267, 268, 270, 270, 272, 278, 278, 283, 285, 300, 300, 308, 327, 334, 336,
                353, 393])

# Perform normality test
result = stats.normaltest(data)
# Extract test statistics and p-value
test_statistic = result.statistic
p_value = result.pvalue
# Print the results
print("Test Statistic:", test_statistic)
print("p-value:", p_value)

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
data = np.array([167, 184, 192, 198, 200, 202, 210, 211, 212, 215, 216, 217, 218, 220, 225,
                225, 226, 230, 230, 230, 230, 231, 232, 232, 232, 234, 234, 236, 236, 238,
                240, 243, 246, 247, 248, 254, 254, 254, 256, 256, 258, 263, 264, 267, 267,
                267, 268, 270, 270, 272, 278, 278, 283, 285, 300, 300, 308, 327, 334, 336,
                353, 393])

# Plot histogram
plt.hist(data, bins='auto', density=True, alpha=0.7, color='skyblue', edgecolor='black')
# Plot kurva distribusi normal
mu, std = np.mean(data), np.std(data)
x = np.linspace(np.min(data), np.max(data), 100)
y = stats.norm.pdf(x, mu, std)
plt.plot(x, y, color='red')
# Set plot title and labels
plt.title('Histogram of Data with Normal Distribution')
plt.xlabel('Data')
plt.ylabel('Frequency')
# Show the plot
plt.show()

# QQ plot
plt.figure(figsize=(6, 4))
stats.probplot(data, dist="norm", plot=plt)
# Set plot title and labels
plt.title('QQ Plot')
plt.xlabel('Theoretical Quantiles')
plt.ylabel('Sample Quantiles')
# Show the plot
plt.show()
# sumber data : https://www.statext.com/practice/NormalityTest02.php

#Python untuk visualisasi normalitas data menggunakan QQ plot dengan menggunakan
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
data = np.array([167, 184, 192, 198, 200, 202, 210, 211, 212, 215, 216, 217, 218, 220, 225,
                225, 226, 230, 230, 230, 230, 231, 232, 232, 232, 234, 234, 236, 236, 238,
                240, 243, 246, 247, 248, 254, 254, 254, 256, 256, 258, 263, 264, 267, 267,
                267, 268, 270, 270, 272, 278, 278, 283, 285, 300, 300, 308, 327, 334, 336,
                353, 393])

# Generate QQ plot
sns.set(style="whitegrid")
stats.probplot(data, dist="norm", plot=sns.mpl.pyplot)
# Set plot title and labels
sns.mpl.pyplot.title('QQ Plot')
sns.mpl.pyplot.xlabel('Theoretical Quantiles')
sns.mpl.pyplot.ylabel('Sample Quantiles')
# Show the plot
sns.mpl.pyplot.show()



import numpy as np
from scipy import stats

data = np.array([167, 184, 192, 198, 200, 202, 210, 211, 212, 215, 216, 217, 218, 220, 225,
                225, 226, 230, 230, 230, 230, 231, 232, 232, 232, 234, 234, 236, 236, 238,
                240, 243, 246, 247, 248, 254, 254, 254, 256, 256, 258, 263, 264, 267, 267,
                267, 268, 270, 270, 272, 278, 278, 283, 285, 300, 300, 308, 327, 334, 336,
                353, 393])

# Kolmogorov-Smirnov Test
ks_statistic, ks_pvalue = stats.kstest(data, 'norm')
print("Kolmogorov-Smirnov Test:")
print("Test Statistic:", ks_statistic)
print("p-value:", ks_pvalue)

# Shapiro-Wilk Test
sw_statistic, sw_pvalue = stats.shapiro(data)
print("\nShapiro-Wilk Test:")
print("Test Statistic:", sw_statistic)
print("p-value:", sw_pvalue)

# Jarque-Bera Test
jb_statistic, jb_pvalue = stats.jarque_bera(data)
print("\nJarque-Bera Test:")
print("Test Statistic:", jb_statistic)
print("p-value:", jb_pvalue)

"""#Uji Normalitas"""

# Uji normalitas
import numpy as np
import matplotlib.pyplot as plt
# Generate random data
np.random.seed(0)
tahun = np.arange(1, 11) # Variabel independen tahun
var1 = np.random.normal(0, 1, 10) # Variabel independen 1 (nilai random yan
#var2 = np.random.normal(0, 1, 10) # Variabel independen 2 (nilai random ya
#nilai_y = 2 * variabel1 + 3 * variabel2 + np.random.normal(0, 1, 10) # Var
# Plot histogram
plt.hist(data, bins=30, edgecolor='black', alpha=0.7)
plt.xlabel('Nilai')
plt.ylabel('Frekuensi')
plt.title('Histogram Data')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# 1. Menentukan seed agar hasil angka acak konsisten
np.random.seed(42)

# 2. Membuat data terdistribusi normal dengan 1000 sampel
# (Jumlah 1000 sampel diperlukan agar tinggi frekuensi histogram mencapai ~80 seperti pada gambar)
data = np.random.normal(loc=0, scale=1, size=1000)

# 3. Membuat plot histogram
plt.figure(figsize=(8, 5.5))
plt.hist(
    data,
    bins=30,
    color="#5B9BD5",  # Warna biru sesuai tampilan gambar
    edgecolor="black",  # Garis tepi hitam antar batang
    linewidth=0.8,
    alpha=0.85,
)

# 4. Menambahkan label dan judul
plt.xlabel("Nilai", fontsize=11)
plt.ylabel("Frekuensi", fontsize=11)
plt.title("Histogram Data", fontsize=13)

# 5. Menampilkan grid di belakang batang histogram
plt.gca().set_axisbelow(True)
plt.grid(True, linestyle="-", alpha=0.5)

# 6. Menampilkan grafik
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Generate random data
np.random.seed(0)
tahun = np.arange(1, 11)
var1 = np.random.normal(0, 1, 1000) # data lebih banyak agar distribusi ter

# Hitung mean dan standar deviasi
mu, sigma = np.mean(var1), np.std(var1)

# Plot histogram
count, bins, ignored = plt.hist(var1, bins=30, density=True, edgecolor='black')

# Plot kurva distribusi normal
x = np.linspace(min(bins), max(bins), 100)
pdf = norm.pdf(x, mu, sigma) # fungsi kepadatan probabilitas normal
plt.plot(x, pdf, 'r-', linewidth=2, label=f'N({mu:.2f}, {sigma:.2f}²)')

# Tambahkan label dan grid
plt.xlabel('Nilai')
plt.ylabel('Kepadatan Frekuensi')
plt.title('Histogram dan Kurva Distribusi Normal')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

import scipy.stats as stats

# Uji normalitas data koding di atas
_, p_value = stats.shapiro(var1)

# Cetak hasil uji normalitas
alpha = 0.05 # Tingkat signifikansi
if p_value > alpha:
 print("Data terdistribusi normal")
else:
 print("Data tidak terdistribusi normal")

"""Uji Asumsi Klasik"""

# Regresi uji asums Klasik
import numpy as np
import matplotlib.pyplot as plt

# Generate random data
np.random.seed(0)
tahun = np.arange(1, 11) # Variabel independen tahun
var1 = np.random.normal(0, 1, 10) # Variabel independen 1 (nilai random yang
var2 = np.random.normal(0, 1, 10) # Variabel independen 2 (nilai random yang
nilai_y = 2 * var1 + 3 * var2 + np.random.normal(0, 1, 10)

# Perform linear regression
X = np.column_stack((var1, var2)) # Matrix X dengan variabel independen
X = np.column_stack((np.ones(len(tahun)), X)) # Tambahkan kolom untuk inter
beta = np.linalg.inv(X.T @ X) @ X.T @ nilai_y # Hitung parameter beta (koefisien)

print("Koefisien Regresi:")
for i in range(len(beta)):
    print(f"Beta{i}: {beta[i]}")

# Plotting data dan regresi
fig, ax = plt.subplots()
ax.scatter(tahun, nilai_y, color='blue', label='Data')
ax.plot(tahun, X @ beta, color='red', label='Regresi')
ax.set_xlabel('Tahun')
ax.set_ylabel('Nilai Y')
ax.legend()
plt.show()

"""##Uji Autokorelasi"""

# Uji Autokorelasi
import statsmodels.api as sm
import matplotlib.pyplot as plt

# Menghitung ACF
acf = sm.tsa.acf(nilai_y)

# Plot ACF
fig, ax = plt.subplots()
ax.bar(range(len(acf)), acf)
ax.axhline(y=0, color='black', linestyle='--')
ax.set_xlabel('Lag')
ax.set_ylabel('Autocorrelation')
ax.set_title('Autocorrelation Function')
plt.show()

"""##HETEROSKEDAStisitas : uji white"""

