# -*- coding: utf-8 -*-
"""PDS1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10jsI6vpYjE-AKkJBOPKwer-gQv15rDDH

#NUMPY
"""

import numpy as np
#membuat array
nilai = np.array([85, 55,40,90])
print(nilai[3])

"""##Indexing and slicing"""

#Manampilkan data
data = np.array([1, 2, 3])
data[1]
data[0:2]
data[1:]
data[-2:]

"""##ndarray.shape"""

#Menampilkan array 2 dimensi setiap dimensi memiliki 3 elemen.
a=np.array([[1,2,3],[4,5,6]])
a.shape

a=np.array([[1,2,3,4],[5,66,7,8])

a=np.array([[1,2,3,4],[5,66,7,8]])
a.shape

a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
b

b = a.reshape(3,2) mengubah ukuran

a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
b

#b = a.reshape(3,2) mengubah ukuran matriks dari matrix 2x3 menjadi 3x2

a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,3)
b

#b = a.reshape(3,3) mengubah ukuran matriks dari matrix 2x3 menjadi 3x3

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a.reshape(3,3)
b
#b = a.reshape(3,3) mengubah ukuran matriks menjadi 3×3

#membuat array sebanyak 24, dari 0-23 #~(0,24)
a = np.arange(24)
b = a.reshape(2, 3, 4)
b

#Membuat array sebanyak 24, dari 0-23 #~(0,24)
a = np.arange(24)
b = a.reshape(2, 4, 3)
b

"""##numpy.arange"""

a = np.arange(24)
a
#Membuat array berurutan dengan nilai mulai dari 0 hingga jumlah elemen yang ditentukan sebagai argumen.

#Membuat array dengan arange
np.arange(3,7)

np.arange(3)

np.arange(3.0)

np.arange(2,12,3)
 #2: awal, 12: end, 3: step

np.arange(2,6,5)

np.arange(3,10,3)

"""##numpy.linspace"""

import numpy as np
# Membuat urutan dari 0 hingga 1 dengan 5 elemen

urutan, jarak = np.linspace(0, 1, 5, retstep=True)
print("Urutan:", urutan)
print("Jarak antara elemen:", jarak)

#Membuat urutan bilangan bulat dari 0 hingga 10 dengan 4 elemen dan tipe data integer
urutan = np.linspace(0, 10, 4, dtype=int)

print("Urutan:", urutan)

#Membuat urutan dengan num=5 tanpa menggunakan endpoint dan dengan menggunakan retstep
a = np.linspace(2.0, 3.0, num=5)
b = np.linspace(2.0, 3.0, num=5, endpoint=False)
c, step = np.linspace(2.0, 3.0, num=5, retstep=True)

# Menampilkan output
print("Urutan a (dengan endpoint):")
print(a)

print("\nUrutan b (tanpa endpoint):")
print(b)

print("\nUrutan c (dengan retstep):")
print(c)

print("\nJarak antara elemen dalam urutan c:")
print(step)

"""#PANDAS"""

#P1
#Running pandas dan numpy
import pandas as pd
import numpy as np


#Menampilkan array 1-dimensi
ds = pd.Series([2, 4, 6, 8, 10])
print(ds)

#P2
data = pd.Series(['a','b','c']) #!sS
np1 = np.array(['x','y','z'])
data_np = pd.Series(np1)

print(data)
print(data_np)

#Mengatur indeks pada numpy array data-np di atas
data_np = pd.Series(np1, index=[2,3,4])
print(data_np)

#P3 contoh operasi
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
dsa = ds1 + ds2  #operasi jumlah
dsb = ds1 - ds2
dsc = ds1 * ds2
dsd = ds1 / ds2
print(dsa)
print(dsb)
print(dsc)
print(dsd)

#P4 konver pandas module Series ke python list
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series dan type")
print(ds)
print(type(ds))

print("Konver Pandas Series ke Python list")
print(ds.tolist())
print(type(ds.tolist()))

#P5 convert a NumPy array to a Pandas series
import numpy as np
import pandas as pd
np_array = np.array([0, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)

new_np = pd.Series(np_array)
print("konversi Pandas series:")
print(new_np)

#P6
import pandas as pd
import numpy as np

#generate angka random
num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10, 4, 20))

print(num_series)
#print(num_state)

df = pd.read_csv('https://raw.githubusercontent.com/Alam-A99/Pandas_Latih/main/penjualan.csv')
df

df.head(3)

df.describe()

"""##Load Data"""

df = pd.read_csv('https://raw.githubusercontent.com/Alam-A99/DATAAKSI/main/dataset_fiskal_97_hipoFull.csv')
df

df.info('kota')

df.describe()

df.tail(4)

df.head(3)

"""## Ekstrak dan manipulasi data frame"""



#P8 menampilkan tabel penjulan februari Jalankan perintah P8 jika file ada di drive local

import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Alam-A99/Pandas_Latih/main/penjualan.csv')

feb = df["feb"]
feb.head()

#P9 Jika akan menampilkan lebih dari satu kolom (Series), gukanan double bracket [[]]

df= pd.read_csv('https://raw.githubusercontent.com/Alam-A99/Pandas_Latih/main/penjualan.csv')
df[['feb','mar']].head(3)

#P10.1

penjual = ['penjual no ' + str(i) for i in range(1, 11)]
penjual

#P10.2

df['urutan'] = penjual
df

#P11 Ekstraksi Angka dari Teks

df['no'] = df['urutan'].str.extract('(\d+)').astype('int64')
df