# -*- coding: utf-8 -*-
"""Visualisasi. ipymb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1USyE8of0FPY_BH9qDTYbzLUrJClBtfXb
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

plt.style.available

plt.style.use('ggplot')

plt.style.use('ggplot')

x = np.linspace(0, 10, 100)
y = np.tan(x)

plt.plot(x, y)
plt.title("Contoh Grafik dengan Style")
plt.show()

x = [1,2,3,4,5]
y = [3,5,-77,19,12]

plt.plot(x,y)

plt.title("Grafik Sederhana")
plt.xlabel ('Nilai X')
plt.ylabel ('Nilai Y')

plt.show()

#numpy random
import numpy as np
from numpy.random import rand

x, y = rand(2,100)
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot
Bulan = ['Jan', 'Feb', 'Mar', 'April', 'Mei']
Penjualan = [150, 200, 180, 250, 125]

plt.figure(figsize=(8,4))

plt.bar(Bulan, Penjualan, color='blue')
plt.title('Penjualan per Bulan')
plt.xlabel('Bulan')
plt.ylabel('Jumlah')

plt.show()

Bulan = ['Jan', 'Feb', 'Mar', 'April', 'Mei']
Penjualan = [150, 200, 180, 250, 125]

plt.figure(figsize=(8,4))

plt.barh(Bulan, Penjualan, color='blue')
plt.title('Penjualan per Bulan')
plt.xlabel('Bulan')
plt.ylabel('Jumlah')

for i, nilai in enumerate(Penjualan):
    plt.text(nilai +2, i, str(nilai), va='center', fontsize=14, color='red', fontweight='bold')

plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Data
bulan = ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Juni', 'Juli']
penjualan = [150, 200, 180, 250, 125, 220, 310]

# Ukuran gambar (diperlebar agar 7 bulan muat dengan rapi)
plt.figure(figsize=(8, 4))

# 1. Buat Grafik Batang
sns.barplot(x=bulan, y=penjualan, hue=bulan, palette='muted', legend=False)

# 2. Tambahkan Garis Tren (Menghubungkan puncak batang)
# range(len(bulan)) menghasilkan [0, 1, 2, 3, 4, 5, 6] sebagai posisi sumbu X
plt.plot(
    range(len(bulan)),  # Posisi X (tengah setiap batang)
    penjualan,          # Posisi Y (nilai penjualan)
    color='red',        # Warna garis
    marker='o',         # Tambahkan titik bulat di setiap persimpangan
    linestyle='-',      # Gaya garis (solid)
    linewidth=2,        # Ketebalan garis
    label='Garis Tren'  # Nama untuk legenda
)

# 3. Kustomisasi Tampilan
plt.title('Penjualan per Bulan dengan Garis Tren', fontsize=12, fontweight='bold')
plt.xlabel('Bulan')
plt.ylabel('Jumlah Penjualan')
plt.legend()  # Menampilkan kotak legenda

plt.tight_layout()
plt.show()

import plotly.express as px
import pandas as pd

# Data (Plotly lebih suka data dalam bentuk DataFrame)
df = pd.DataFrame({
    'Bulan': ['Jan', 'Feb', 'Mar', 'Apr', 'Mei'],
    'Penjualan': [150, 200, 180, 250, 300]
})

# Membuat grafik dasar
fig = px.bar(df, x='Bulan', y='Penjualan', title='Penjualan per Bulan (Plotly)')

fig.update_layout(width=700, height=400) # pixel

# Menampilkan grafik
fig.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Muat dataset dari URL
url = "https://raw.githubusercontent.com/Alam-A99/Pandas_Latih/10ebb3af000e930a44989075733f495d5c2f4be5/penjualan.csv"
df = pd.read_csv(url)

# 2. Tambahkan kolom total untuk memudahkan beberapa grafik
df['total'] = df[['jan', 'feb', 'mar', 'apr']].sum(axis=1)

# Atur style seaborn agar lebih rapi
sns.set_theme(style='whitegrid')

# 1. Bar Chart
plt.figure(figsize=(8, 5))  # Ukuran kompak (lebar 8, tinggi 5 inci)

# Urutkan data dari total tertinggi
df_sorted = df.sort_values('total', ascending=False)

# Membuat barplot dengan parameter hue, palette, dan legend=False untuk menghindari warning
sns.barplot(
    data=df_sorted,
    x='nama',
    y='total',
    hue='nama',
    palette='viridis',
    legend=False
)

plt.title('Total Penjualan per Orang', fontsize=12)
plt.xlabel('Nama Karyawan')
plt.ylabel('Total Penjualan')
plt.xticks(rotation=45)  # Miringkan label agar tidak tumpang tindih
plt.tight_layout()

plt.show()

# Pie Chart
plt.figure(figsize=(5, 5))  # Ukuran persegi agar pie chart tidak gepeng

# Hitung total penjualan per bulan
total_per_bulan = df[['jan', 'feb', 'mar', 'apr']].sum()

plt.pie(
    total_per_bulan,
    labels=total_per_bulan.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=sns.color_palette('muted')
)

plt.title('Proporsi Penjualan per Bulan', fontsize=12)
plt.tight_layout()
plt.show()

import pandas as pd
import plotly.express as px

# Ubah format data menjadi "long" (khusus mengambil kolom 'jan' dan 'mar')
df_melted = df.melt(id_vars=['nama'], value_vars=['jan', 'mar'], var_name='Bulan',
                    value_name='Penjualan')

# Buat Line Chart (Hanya butuh 1 blok kode inti!)
fig = px.line(
    df_melted, x='nama', y='Penjualan', color='Bulan', symbol='Bulan',
    symbol_sequence=['circle', 'triangle-up'], color_discrete_sequence=['royalblue', 'crimson'],
    markers=True,
    title='Perbandingan Penjualan: Januari vs Maret',
    labels={'nama': 'Nama Karyawan', 'Penjualan': 'Jumlah Penjualan'}
)

# Atur ukuran agar tidak full screen (Opsional)
fig.update_layout(width=800, height=500)

# 5. Tampilkan grafik
fig.show()

import pandas as pd

url = "https://raw.githubusercontent.com/Alam-A99/DATAAKSI/refs/heads/main/dataset_fiskal_97_hipoFull.csv"
df1 = pd.read_csv(url)

#df1.info()
#df1.shape
#df1.columns
df1.describe()

import pandas as pd

kol_pilihan = ['PAD', 'KEMISKINAN', 'PENGANGGURAN', 'IPM']

# Pilih kolom tersebut, lalu panggil describe()
hasil_deskriptif = df1[kol_pilihan].describe()

print(hasil_deskriptif)

# Boxplot (Sebaran IPM & Outlier)
# Melihat median, kuartil, dan daerah mana yang menjadi outlier (pencilan) dalam IPM.
plt.figure(figsize=(6, 5))
sns.boxplot(data=df1, y='IPM', color='skyblue', width=0.4)

plt.title('Sebaran Indeks Pembangunan Manusia (IPM)', fontsize=12, fontweight='bold')
plt.ylabel('Nilai IPM (0-100)')
plt.tight_layout()
plt.show()